// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Infrastructure.Persistence;

#nullable disable

namespace ShoppingCart.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20260715050138_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Technology",
                            Code = "PRD-001",
                            Name = "Mechanical Keyboard",
                            Price = 80m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Technology",
                            Code = "PRD-002",
                            Name = "Wireless Mouse",
                            Price = 35m,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Monitors",
                            Code = "PRD-003",
                            Name = "Monitor 24 Inches",
                            Price = 180m,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Accessories",
                            Code = "PRD-004",
                            Name = "USB Webcam",
                            Price = 55m,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Computers",
                            Code = "PRD-005",
                            Name = "Laptop",
                            Price = 850m,
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Audio",
                            Code = "PRD-006",
                            Name = "Gaming Headset",
                            Price = 95m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("ShoppingCart.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "customer@shoppingcart.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEPOxdB34UwagFKUgkIkXgQsot0S5P7e8NjUAEJm1JWi2XnLEhOG2hRVpZLzyjYdMqA==",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "admin@shoppingcart.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEA/Ba/aYaifQlnE3UhFCCrzC96HRonJiOV4iHNeWk+1/C4+y/6EosmK3XQZyxYjmyQ==",
                            Role = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
